In [2]:
import arxiv

search = arxiv.Search(
    query="cat:cs.AI",
    max_results=10,
    sort_by=arxiv.SortCriterion.SubmittedDate
)

client = arxiv.Client()
papers = list(client.results(search))

for paper in papers:
    print(paper.title)
    print(paper.published)
    print(paper.entry_id)
    print("-" * 50)

FurE: Efficient Instance-Specific 3D Fur Reconstruction without Animal-Fur Datasets
2026-09-28 17:59:58+00:00
http://arxiv.org/abs/2609.35770v1
--------------------------------------------------
Telescopic Language Models
2026-09-28 17:59:53+00:00
http://arxiv.org/abs/2609.35769v1
--------------------------------------------------
Learning Native Reflection in Unified Models with Interleaved Reinforcement Learning
2026-09-28 17:59:36+00:00
http://arxiv.org/abs/2609.35767v1
--------------------------------------------------
TokenCast: Forecasting Token Consumption During LLM Agent Execution
2026-09-28 17:59:09+00:00
http://arxiv.org/abs/2609.35760v1
--------------------------------------------------
How to Loop MoE: Flatten the Experts, Untie the Attention
2026-09-28 17:58:03+00:00
http://arxiv.org/abs/2609.35751v1
--------------------------------------------------
KV-streams for Efficient Compaction in Agentic Reinforcement Learning
2026-09-28 17:57:42+00:00
http://arxiv.org/abs/2609.35750v1
--------------------------------------------------
Copy the Same, Distill the Difference: Initializing Linear Vision Transformers
2026-09-28 17:55:21+00:00
http://arxiv.org/abs/2609.35745v1
--------------------------------------------------
FinAutoRubric: Expert-Guided Automatic Rubric Generation for Evaluating Financial Research Agents
2026-09-28 17:55:06+00:00
http://arxiv.org/abs/2609.35744v1
--------------------------------------------------
Shockingly Simple Self-retrospection Improves Agentic Models Without RL
2026-09-28 17:54:24+00:00
http://arxiv.org/abs/2609.35741v1
--------------------------------------------------
Failure-Transparent Agents: Benchmarking Post-Failure Reporting in Tool-Using Language Models
2026-09-28 17:51:41+00:00
http://arxiv.org/abs/2609.35732v1
--------------------------------------------------

In [3]:
paper = papers[0]

print("Title:", paper.title)
print("Authors:", [author.name for author in paper.authors])
print("Published:", paper.published)
print("Categories:", paper.categories)
print("PDF URL:", paper.pdf_url)
print("Entry ID:", paper.entry_id)
print("\nAbstract:\n", paper.summary)

Title: FurE: Efficient Instance-Specific 3D Fur Reconstruction without Animal-Fur Datasets
Authors: ['Srinjay Sarkar', 'Prakhar Kaushik', 'Soumava Paul', 'Alan Yuille']
Published: 2026-09-28 17:59:58+00:00
Categories: ['cs.CV', 'cs.AI', 'cs.GR']
PDF URL: https://arxiv.org/pdf/2609.35770v1
Entry ID: http://arxiv.org/abs/2609.35770v1

Abstract:
 Realistic and editable animal fur reconstruction from multi-view images is challenging due to fine-scale detail, self-occlusion and obfuscation, and, unlike human hair, the lack of animal-fur datasets. Fur usually covers most of an animal's body, with large inter-species and intra-species variability. We present FurE, an efficient strand-based animal fur reconstruction method that recovers a per-strand, editable groom by optimizing a root-conditioned latent field, decoded into strand geometry via a PCA-based decoder. We reconstruct a defurred animal body using local fur-thickness cues from a surface-constrained Gaussian Frosting representation together with part-based priors. We further show that a PCA-based decoder learned from human-hair strand data can alleviate animal-data scarcity while enabling substantially faster optimization. FurE achieves a 10x speedup in strand training over current SOTA dense per-strand optimization while retaining strand fidelity and generalizing across synthetic and real-world sequences, with quantitative and qualitative validation despite the reduction in training time.

In [4]:
import pandas as pd

data = []

for paper in papers:
    data.append({
        "title": paper.title,
        "authors": [author.name for author in paper.authors],
        "published": paper.published,
        "categories": paper.categories,
        "pdf_url": paper.pdf_url,
        "entry_id": paper.entry_id,
        "abstract": paper.summary
    })

df = pd.DataFrame(data)

df.head()

,title,authors,published,categories,pdf_url,entry_id,abstract
0,FurE: Efficient Instance-Specific 3D Fur Recon...,"[Srinjay Sarkar, Prakhar Kaushik, Soumava Paul...",2026-09-28 17:59:58+00:00,"[cs.CV, cs.AI, cs.GR]",https://arxiv.org/pdf/2609.35770v1,http://arxiv.org/abs/2609.35770v1,Realistic and editable animal fur reconstructi...
1,Telescopic Language Models,"[Zhilin Guo, Boqiao Zhang, Hakan Aktas, Kyle F...",2026-09-28 17:59:53+00:00,"[cs.CL, cs.AI]",https://arxiv.org/pdf/2609.35769v1,http://arxiv.org/abs/2609.35769v1,One deployed language model must often serve m...
2,Learning Native Reflection in Unified Models w...,"[Yijia Fan, Ziqi Huang, Zhongang Cai, Yan Li, ...",2026-09-28 17:59:36+00:00,"[cs.CV, cs.AI]",https://arxiv.org/pdf/2609.35767v1,http://arxiv.org/abs/2609.35767v1,Unified multimodal models can both look at and...
3,TokenCast: Forecasting Token Consumption Durin...,"[Chaoqian Ouyang, Ling Yue, Libin Zheng, Huang...",2026-09-28 17:59:09+00:00,"[cs.LG, cs.AI, cs.SE]",https://arxiv.org/pdf/2609.35760v1,http://arxiv.org/abs/2609.35760v1,When a large language model (LLM) agent execut...
4,"How to Loop MoE: Flatten the Experts, Untie th...","[Shouren Wang, Chuang Ma, Mohsen Hariri, Debar...",2026-09-28 17:58:03+00:00,"[cs.LG, cs.AI, cs.CL]",https://arxiv.org/pdf/2609.35751v1,http://arxiv.org/abs/2609.35751v1,Looped Transformers reuse one block of layers ...

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       10 non-null     str
 1   authors     10 non-null     object
 2   published   10 non-null     datetime64[us, UTC]
 3   categories  10 non-null     object
 4   pdf_url     10 non-null     str
 5   entry_id    10 non-null     str
 6   abstract    10 non-null     str
dtypes: datetime64[us, UTC](1), object(2), str(4)
memory usage: 692.0+ bytes

In [6]:
df.isnull().sum()

title         0
authors       0
published     0
categories    0
pdf_url       0
entry_id      0
abstract      0
dtype: int64

In [7]:
df["abstract_length"] = df["abstract"].str.len()

df[["title", "abstract_length"]]

                                               title  abstract_length
0  FurE: Efficient Instance-Specific 3D Fur Recon...             1118
1                         Telescopic Language Models             1606
2  Learning Native Reflection in Unified Models w...             1352
3  TokenCast: Forecasting Token Consumption Durin...             1339
4  How to Loop MoE: Flatten the Experts, Untie th...             1683
5  KV-streams for Efficient Compaction in Agentic...             1275
6  Copy the Same, Distill the Difference: Initial...             1804
7  FinAutoRubric: Expert-Guided Automatic Rubric ...             1264
8  Shockingly Simple Self-retrospection Improves ...             1810
9  Failure-Transparent Agents: Benchmarking Post-...             1199

In [8]:
df["abstract_length"].describe()

count      10.000000
mean     1445.000000
std       256.831549
min      1118.000000
25%      1266.750000
50%      1345.500000
75%      1663.750000
max      1810.000000
Name: abstract_length, dtype: float64

In [9]:
from collections import Counter

category_counts = Counter(
    category
    for categories in df["categories"]
    for category in categories
)

category_counts

Counter({'cs.AI': 10,
         'cs.LG': 4,
         'cs.CV': 3,
         'cs.CL': 3,
         'cs.GR': 1,
         'cs.SE': 1,
         'q-fin.CP': 1})

The initial sample contains complete metadata with no missing values. Abstracts average about 1,431 characters. All papers are categorized as cs.AI, while some also belong to additional categories such as computer vision, human-computer interaction, machine learning, and robotics. This suggests that category filtering alone may not be enough to determine business relevance.

In [10]:
df["entry_id"].duplicated().sum()

np.int64(0)

In [11]:
df["title"].duplicated().sum()

np.int64(0)

In [12]:
print("Earliest:", df["published"].min())
print("Latest:", df["published"].max())

Earliest: 2026-09-28 17:51:41+00:00
Latest: 2026-09-28 17:59:58+00:00

In [13]:
df["author_count"] = df["authors"].apply(len)
df["author_count"].describe()

count    10.000000
mean     11.500000
std       5.212165
min       4.000000
25%       8.250000
50%      10.000000
75%      15.750000
max      20.000000
Name: author_count, dtype: float64

In [14]:
for i in range(min(3, len(df))):
    print(df.loc[i, "title"])
    print(df.loc[i, "abstract"][:500])
    print("-" * 80)

FurE: Efficient Instance-Specific 3D Fur Reconstruction without Animal-Fur Datasets
Realistic and editable animal fur reconstruction from multi-view images is challenging due to fine-scale detail, self-occlusion and obfuscation, and, unlike human hair, the lack of animal-fur datasets. Fur usually covers most of an animal's body, with large inter-species and intra-species variability. We present FurE, an efficient strand-based animal fur reconstruction method that recovers a per-strand, editable groom by optimizing a root-conditioned latent field, decoded into strand geometry vi
--------------------------------------------------------------------------------
Telescopic Language Models
One deployed language model must often serve many compute budgets, yet serving each budget still means a separate training or compression run per point. We train a Telescopic Language Model (TLM) to be that continuum: a nested-capacity Transformer supervised by stochastic prefix supervision with a full anchor. At every step, one randomly truncated prefix of the capacity axis is trained against the full next-token target, alongside one full-capacity pass, so the trained artifact is a valid langua
--------------------------------------------------------------------------------
Learning Native Reflection in Unified Models with Interleaved Reinforcement Learning
Unified multimodal models can both look at and render images, so in principle they can repair their own generations: diagnose what an image gets wrong, revise it, observe the result, and diagnose again. Whether a revision helps is known only after it is rendered, so the reflection text and the image generation must be learned jointly, over the whole loop. Supervised fine-tuning (SFT) on reflection trajectories gives a cold start but does not find the high-success repair paths, and naive RL that
--------------------------------------------------------------------------------

## Larger Sample Exploration

In [15]:
search_100 = arxiv.Search(
    query="cat:cs.AI",
    max_results=100,
    sort_by=arxiv.SortCriterion.SubmittedDate
)

papers_100 = list(client.results(search_100))

data_100 = []

for paper in papers_100:
    data_100.append({
        "title": paper.title,
        "authors": [author.name for author in paper.authors],
        "published": paper.published,
        "categories": paper.categories,
        "pdf_url": paper.pdf_url,
        "entry_id": paper.entry_id,
        "abstract": paper.summary
    })

df_100 = pd.DataFrame(data_100)

df_100.head()

,title,authors,published,categories,pdf_url,entry_id,abstract
0,FurE: Efficient Instance-Specific 3D Fur Recon...,"[Srinjay Sarkar, Prakhar Kaushik, Soumava Paul...",2026-09-28 17:59:58+00:00,"[cs.CV, cs.AI, cs.GR]",https://arxiv.org/pdf/2609.35770v1,http://arxiv.org/abs/2609.35770v1,Realistic and editable animal fur reconstructi...
1,Telescopic Language Models,"[Zhilin Guo, Boqiao Zhang, Hakan Aktas, Kyle F...",2026-09-28 17:59:53+00:00,"[cs.CL, cs.AI]",https://arxiv.org/pdf/2609.35769v1,http://arxiv.org/abs/2609.35769v1,One deployed language model must often serve m...
2,Learning Native Reflection in Unified Models w...,"[Yijia Fan, Ziqi Huang, Zhongang Cai, Yan Li, ...",2026-09-28 17:59:36+00:00,"[cs.CV, cs.AI]",https://arxiv.org/pdf/2609.35767v1,http://arxiv.org/abs/2609.35767v1,Unified multimodal models can both look at and...
3,TokenCast: Forecasting Token Consumption Durin...,"[Chaoqian Ouyang, Ling Yue, Libin Zheng, Huang...",2026-09-28 17:59:09+00:00,"[cs.LG, cs.AI, cs.SE]",https://arxiv.org/pdf/2609.35760v1,http://arxiv.org/abs/2609.35760v1,When a large language model (LLM) agent execut...
4,"How to Loop MoE: Flatten the Experts, Untie th...","[Shouren Wang, Chuang Ma, Mohsen Hariri, Debar...",2026-09-28 17:58:03+00:00,"[cs.LG, cs.AI, cs.CL]",https://arxiv.org/pdf/2609.35751v1,http://arxiv.org/abs/2609.35751v1,Looped Transformers reuse one block of layers ...

In [19]:
df_100.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       100 non-null    str
 1   authors     100 non-null    object
 2   published   100 non-null    datetime64[us, UTC]
 3   categories  100 non-null    object
 4   pdf_url     100 non-null    str
 5   entry_id    100 non-null    str
 6   abstract    100 non-null    str
dtypes: datetime64[us, UTC](1), object(2), str(4)
memory usage: 5.6+ KB

In [17]:
df_100.isnull().sum()

title         0
authors       0
published     0
categories    0
pdf_url       0
entry_id      0
abstract      0
dtype: int64

In [18]:
print("Duplicate IDs:", df_100["entry_id"].duplicated().sum())
print("Duplicate titles:", df_100["title"].duplicated().sum())

Duplicate IDs: 0
Duplicate titles: 0

In [20]:
df_100["abstract_length"] = df_100["abstract"].str.len()
df_100["abstract_length"].describe()

count     100.000000
mean     1440.290000
std       307.546114
min       311.000000
25%      1267.750000
50%      1453.500000
75%      1676.250000
max      1918.000000
Name: abstract_length, dtype: float64

In [21]:
df_100["author_count"] = df_100["authors"].apply(len)
df_100["author_count"].describe()

count    100.000000
mean       6.210000
std        5.311119
min        1.000000
25%        3.000000
50%        4.500000
75%        8.000000
max       40.000000
Name: author_count, dtype: float64

In [22]:
from collections import Counter

category_counts_100 = Counter(
    category
    for categories in df_100["categories"]
    for category in categories
)

category_counts_100.most_common(15)

[('cs.AI', 100),
 ('cs.LG', 34),
 ('cs.CL', 24),
 ('cs.CV', 9),
 ('cs.CR', 6),
 ('cs.SE', 4),
 ('cs.RO', 4),
 ('cs.GR', 2),
 ('cs.SC', 2),
 ('q-fin.CP', 1),
 ('cs.NE', 1),
 ('cs.DC', 1),
 ('cs.CY', 1),
 ('quant-ph', 1),
 ('cs.AR', 1)]

In [23]:
print("Earliest:", df_100["published"].min())
print("Latest:", df_100["published"].max())

Earliest: 2026-09-28 14:34:23+00:00
Latest: 2026-09-28 17:59:58+00:00

### Larger Sample Findings

The 100-paper sample had no missing values or duplicate papers. Abstract length and author count varied across papers, and many papers belonged to multiple AI-related categories. This shows that category filtering alone may not be enough to determine relevance.

The sample also covers only a few hours from one day, so a larger dataset across a wider date range may be needed. Before building the retrieval pipeline, the data should be cleaned, normalized, and prepared for text chunking and embeddings.

In [24]:
(df_100["abstract"].str.strip() == "").sum()

np.int64(0)